### GET All Patients

http://localhost:8080
### GET Patient by ID
GET http://localhost:8080/weather

### DELETE Patient by ID
GET http://localhost:8080/weather/Kyiv

### Create Patient
POST http://localhost:8080/weather
Content-Type: application/json

{
"city": "Odesa",
"temperature": 16.3,
"description": "Windy"
}


